<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.1.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.0.2" />
    <PackageReference Include="MSTest" Version="4.0.2" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="TYoshimura.Algebra" Version="3.0.0" />
    <PackageReference Include="TYoshimura.DoubleDouble" Version="5.0.1" />
    <PackageReference Include="TYoshimura.DoubleDouble.Complex" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='Debug'">
    <Reference Include="DoubleDoubleStatistic">
      <HintPath>..\DoubleDoubleStatistic\bin\Debug\net10.0\DoubleDoubleStatistic.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='Release'">
    <Reference Include="DoubleDoubleStatistic">
      <HintPath>..\DoubleDoubleStatistic\bin\Release\net10.0\DoubleDoubleStatistic.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
